// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-sD1s3JWe6Bix0zIN8Q7IUFWdgnd0xdM',
    appId: '1:622124934898:web:b941f6fc2f478b86fa526b',
    messagingSenderId: '622124934898',
    projectId: 'todo-app-ca9dc',
    authDomain: 'todo-app-ca9dc.firebaseapp.com',
    storageBucket: 'todo-app-ca9dc.firebasestorage.app',
    measurementId: 'G-H2C7CBQHLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAJCGCllxMvezhe-R0ISHwsj-FYARBn7A',
    appId: '1:622124934898:android:605a7eeaafca16d7fa526b',
    messagingSenderId: '622124934898',
    projectId: 'todo-app-ca9dc',
    storageBucket: 'todo-app-ca9dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV3yTqociIHtZ-rQcL4_aSnGtxh0Bo8Zo',
    appId: '1:622124934898:ios:9ef6cdb0a1e0d64bfa526b',
    messagingSenderId: '622124934898',
    projectId: 'todo-app-ca9dc',
    storageBucket: 'todo-app-ca9dc.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV3yTqociIHtZ-rQcL4_aSnGtxh0Bo8Zo',
    appId: '1:622124934898:ios:9ef6cdb0a1e0d64bfa526b',
    messagingSenderId: '622124934898',
    projectId: 'todo-app-ca9dc',
    storageBucket: 'todo-app-ca9dc.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-sD1s3JWe6Bix0zIN8Q7IUFWdgnd0xdM',
    appId: '1:622124934898:web:2158afaaab70875afa526b',
    messagingSenderId: '622124934898',
    projectId: 'todo-app-ca9dc',
    authDomain: 'todo-app-ca9dc.firebaseapp.com',
    storageBucket: 'todo-app-ca9dc.firebasestorage.app',
    measurementId: 'G-MMKCZPLJPX',
  );
}
